// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpdudhqqkmroqqanjame.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZHVkaHFxa21yb3FxYW5qYW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTEzMTEsImV4cCI6MjA1NzU4NzMxMX0.Juw8ICyQq7DMm8PI7qbU4qoLCZsHnNrwB6tPNMEp4ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);